### PR TITLE
Disable dependabot notifications

### PR DESCRIPTION
**Pull request by PrashantR31**
#### Overview

The PR removes the file https://github.com/giantswarm/dex/blob/master/.github/dependabot.yaml from giantswarm/dex, so that dependabot does not send any notification 
Reference from issue: https://github.com/giantswarm/giantswarm/issues/20089

### CODE REVIEW

**Review by anvddriesch — APPROVED** [review]

**Comment by PrashantR31** [comment]
Thanks @anvddriesch

**Comment by marians** [comment]
@PrashantR31 I think you wanted to merge this PR but in fact closed it instead.

**Comment by PrashantR31** [comment]
Ooops. let me reopen and merge.

**Comment by PrashantR31** [comment]
Thanks @marians for checking. Code is now merged successfully.

**Pull request merged**
